// Generated by scripts/photos.mjs from the originals: do not edit by hand.
import type { PhotoMeta } from "./types";

export const photoMeta: Record<string, PhotoMeta> = {
  "MX2-04": { w: 1350, h: 2400, blur: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoJABAABABoJYgCdEf/gYfnYZgAAPzU5rX2hnUrnOHXsLFFzQm09Af1u9JUvRkPY4mB2Dk7zIxskwLyP3coklL77i3LjfdocvytQvF16HwAAA==" },
  "MX2-04-band": { w: 2268, h: 1134, blur: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoJABAABABoJYgCdEf/gYfnYZgAAPzU5rX2hnUrnOHXsLFFzQm09Af1u9JUvRkPY4mB2Dk7zIxskwLyP3coklL77i3LjfdocvytQvF16HwAAA==" },
  "MX2-01": { w: 1350, h: 2400, blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoJABAABABoJYgCw7DbAMNJAAD+mPfFtlGY6+rzmlBB8g0NTF88tmaQH8V6hS9eYn63LnzZVc9wvj1L89ZZg5U/uVIjAJqwWCIdUwAA" },
  "MX2-02": { w: 1351, h: 2400, blur: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoJABAABABoJYgC7AD5ifr6BT4AAPaRJYCdwBwtQONB0odohIGPB0lQJoK+Fa6J6wAY0V7Jt2q/3I+7FOHcxClzaVmsU3HxEj1KgAAA" },
  "MX2-03": { w: 1350, h: 2400, blur: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoJABAABABoJYgCdAD0SCQF+wAA/tXlcjFxqnCP+6m89dbK1gXGcUsH4JPfSEpJHd1iWKPuP4WpN3DQD0nUlSqYIgyHNtjUMmI82oFujFybAAAA" },
  "MX2-05": { w: 1350, h: 2400, blur: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoJABAABABoJQBOgBuRA8emCADdjFVbYsxJBTChUq+U+MPxLuHp92Ah9dVx1ROx1WSDhr21TlHZXo8ZzyHVHhSJt2vwAA==" },
  "MX2-06": { w: 1350, h: 2400, blur: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoJABAABABoJQBOgCPw6qO75ui4AP7p401lLfEvp+0s9cyWMUpZqk5PWs5SGytDyZ8sq6WdhS6o/QJBSEYNq3AAAAA=" },
};
